name: vision-robotica
channels:
  - defaults
dependencies:
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.3.0
  - blosc=1.21.0
  - brotli=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2021.5.25
  - certifi=2021.5.30
  - cffi=1.14.5
  - charls=2.2.0
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2021.5.1
  - decorator=5.0.6
  - defusedxml=0.7.1
  - entrypoints=0.3
  - freetype=2.10.4
  - fsspec=0.9.0
  - giflib=5.2.1
  - hdf5=1.8.20
  - icc_rt=2019.0.0
  - icu=58.2
  - imagecodecs=2021.4.28
  - imageio=2.9.0
  - importlib-metadata=3.10.0
  - importlib_metadata=3.10.0
  - intel-openmp=2021.2.0
  - ipykernel=5.3.4
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - jedi=0.17.0
  - jinja2=2.11.3
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - kiwisolver=1.3.1
  - lcms2=2.12
  - lerc=2.2.1
  - libaec=1.0.4
  - libdeflate=1.7
  - libopencv=3.4.2
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.1.0
  - libzopfli=1.0.3
  - locket=0.2.1
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mistune=0.8.4
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - msys2-conda-epoch=20160418
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - networkx=2.2
  - notebook=6.3.0
  - numpy=1.20.1
  - numpy-base=1.20.1
  - olefile=0.46
  - opencv=3.4.2
  - openjpeg=2.3.0
  - openssl=1.1.1k
  - packaging=20.9
  - pandoc=2.12
  - pandocfilters=1.4.3
  - parso=0.8.2
  - partd=1.2.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.0.1
  - prometheus_client=0.10.1
  - prompt-toolkit=3.0.17
  - py-opencv=3.4.2
  - pycparser=2.20
  - pygments=2.8.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - python=3.7.10
  - python-dateutil=2.8.1
  - pywavelets=1.1.1
  - pywin32=227
  - pywinpty=0.5.7
  - pyyaml=5.4.1
  - pyzmq=20.0.0
  - qt=5.9.7
  - scikit-image=0.18.1
  - send2trash=1.5.0
  - setuptools=52.0.0
  - sip=4.19.8
  - six=1.15.0
  - snappy=1.1.8
  - sqlite=3.35.4
  - terminado=0.9.4
  - testpath=0.4.4
  - tifffile=2021.4.8
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - traitlets=5.0.5
  - typing_extensions=3.7.4.3
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - wincertstore=0.2
  - winpty=0.4.3
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.3
  - zfp=0.5.5
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - joblib==1.0.1
    - pandas==1.2.4
    - pytz==2021.1
    - scikit-learn==0.24.2
    - scipy==1.6.3
    - seaborn==0.11.1
    - threadpoolctl==2.1.0
